apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: cnob21lpn-python 
  janus-idp.io/tekton: cnob21lpn-python
  backstage.io/kubernetes-id: cnob21lpn-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cnob21lpn-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml