apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cnob21lpn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cnob21lpn-python 
  name: cnob21lpn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cnob21lpn-python 
